name: Feature Request
title: 'API Endpoint Creation'
description: Please provide details for the new API endpoint you would like to create.
labels:
  - sweep
  - api
body:
  - type: section
    id: request_details
    attributes:
      label: Request Details
      description: Please provide a detailed description of the new API endpoint.
    children:
      - type: textarea
        id: description
        attributes:
          label: Description
          description: Please describe the purpose, functionality, and any relevant details about the new endpoint.
          placeholder: The new endpoint should use the ... class from ... file because it contains ... logic.
          rows: 5
